[package]
name = "crabzzai/simpledialogue"
version = "0.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Fusion = "elttob/fusion@0.2.0"